config/routes.rb
Rails.application.routes.draw do
  resources :games

  get 'home/index'

   root 'home#index'

end

app/models/game.rb
class Game < ActiveRecord::Base
  
  before_create :update_answer
  
  def update_answer
    self.answer = rand(0...10)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def new
    @game = Game.new  
  end
  
  def create
    @game = Game.new
    @game.save!
    
    if @game.answer == params[:guess].to_i
      redirect_to @game, notice: "You guessed right!"
    else 
      redirect_to @game, notice: "You guessed wrong!" 
    end
  end

  def index
    @games = Game.all
  end 

  def show
    @game = Game.find(params[:id])
  end
  
  def update
    @game = Game.find(params[:id])
    
    @game.guess_count += 1
    @game.save! 
    if @game.answer == params[:guess].to_i
      redirect_to @game, notice: "You guessed right!"
        
    else
      redirect_to @game, notice: "You guessed wrong!"
  end
end
  
 private 
  def game_params
    params.require(:game).permit(:guess, :guess_count)
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/games/index.html.erb
<h1> Guessing Numbers! </h1>

<a href ="/games/new">Play new game</a></li>

app/views/games/new.html.erb
<h1> Guessing Numbers! </h1>
<h2> New Game </h2>

<a href ="/games">Back</a></li>

<p>
<%= form_for @game do %>
	<%= label_tag(:q, 'Guess between 1 and 10:') %>
	<%= text_field_tag :guess %>
  <%= submit_tag("Enter guess") %>
<% end %>
</p>

app/views/games/show.html.erb
<h1> Guessing Numbers! </h1>

<p id="notice"><strong><%= flash[:notice] %></strong></p>

..........

<p> <strong>Play again?</strong> 


<%= form_for @game do %>
	<%= label_tag(:q, 'Guess between 1 and 10:') %>
	<%= text_field_tag :guess %>
  <%= submit_tag("Enter guess") %>
<% end %>
</p>

<p><strong>OR</strong></p>

<a href ="/games/new"><strong>Play new game?</strong></a></li>

app/views/home/index.html.erb
<h1>Welcome! </h1>
<%=  link_to 'click to enter and play!', games_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NumberGame</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>